// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Counter$RescriptIntro from "./Counter.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return [
                /* Synced */0,
                1
              ];
      });
  var setIncrement = match[1];
  var match$1 = match[0];
  var increment = match$1[1];
  var onInputIncrement = function (e) {
    var value = Belt_Int.fromString(e.target.value);
    return Curry._1(setIncrement, (function (param) {
                  if (value !== undefined) {
                    return [
                            /* Synced */0,
                            value
                          ];
                  } else {
                    return [
                            /* Cached */1,
                            increment
                          ];
                  }
                }));
  };
  var inputValue = match$1[0] ? "" : String(increment);
  return React.createElement("div", {
              className: "flex flex-col justify-center items-center h-screen gap-6"
            }, React.createElement(Counter$RescriptIntro.make, {
                  increment: increment
                }), React.createElement("input", {
                  className: "px-6 py-3 border border-blue-300 rounded-lg",
                  min: "1",
                  step: 1.0,
                  type: "number",
                  value: inputValue,
                  onInput: onInputIncrement
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
