// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Counter$RescriptIntro from "./Counter.bs.js";
import * as NumberInput$RescriptIntro from "./NumberInput.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return 1;
      });
  var setIncrement = match[1];
  var increment = match[0];
  return React.createElement("div", {
              className: "flex flex-col justify-center items-center h-screen gap-4"
            }, React.createElement(Counter$RescriptIntro.make, {
                  increment: increment
                }), React.createElement(NumberInput$RescriptIntro.Int.make, {
                  value: increment,
                  onInput: (function (i) {
                      return Curry._1(setIncrement, (function (param) {
                                    return i;
                                  }));
                    }),
                  step: 1,
                  min: 1,
                  className: "px-4 py-2 border border-blue-300 rounded-lg"
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
