// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Counter(Props) {
  var startOpt = Props.start;
  var incOpt = Props.increment;
  var start = startOpt !== undefined ? startOpt : 0;
  var inc = incOpt !== undefined ? incOpt : 1;
  var match = React.useState(function () {
        return start;
      });
  var setClicks = match[1];
  var incCount = function (param) {
    return Curry._1(setClicks, (function (clicks) {
                  return clicks + inc | 0;
                }));
  };
  return React.createElement("div", {
              className: "flex justify-center items-center gap-4"
            }, React.createElement("span", {
                  className: "w-20 text-left"
                }, "Clicks: " + String(match[0])), React.createElement("button", {
                  className: "px-6 py-3 bg-blue-400 text-white rounded-lg",
                  onClick: incCount
                }, "+ " + String(inc)));
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
