// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function NumberInput$Int(Props) {
  var value = Props.value;
  var callback = Props.onInput;
  var stepOpt = Props.step;
  var min = Props.min;
  var classNameOpt = Props.className;
  var step = stepOpt !== undefined ? stepOpt : 1;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var match = React.useState(function () {
        return /* Synced */0;
      });
  var setState = match[1];
  var onInput = function (e) {
    var i = Belt_Int.fromString(e.target.value);
    if (i !== undefined) {
      Curry._1(setState, (function (param) {
              return /* Synced */0;
            }));
      return Curry._1(callback, i);
    } else {
      return Curry._1(setState, (function (param) {
                    return /* Empty */1;
                  }));
    }
  };
  var inputValue = match[0] ? "" : String(value);
  return React.createElement("input", {
              className: className,
              min: Belt_Option.mapWithDefault(min, "", (function (prim) {
                      return String(prim);
                    })),
              step: step,
              type: "number",
              value: inputValue,
              onInput: onInput
            });
}

var Int = {
  make: NumberInput$Int
};

export {
  Int ,
  
}
/* react Not a pure module */
