// Generated by ReScript, PLEASE EDIT WITH CARE


function id(x) {
  return x;
}

function $$const(x, param) {
  return x;
}

var $$Function = {
  id: id,
  $$const: $$const
};

function add(x, y) {
  return x + y | 0;
}

function sub(x, y) {
  return y - x | 0;
}

var Int = {
  add: add,
  sub: sub
};

export {
  $$Function ,
  Int ,
  
}
/* No side effect */
