// Generated by ReScript, PLEASE EDIT WITH CARE


function id(x) {
  return x;
}

function $$const(x, param) {
  return x;
}

var $$Function = {
  id: id,
  $$const: $$const
};

export {
  $$Function ,
  
}
/* No side effect */
